'use strict';
/* 内置世界城市（与原机时钟风格一致的中文城市名） */

const CITIES = [
  { id: 'beijing', name: '北京', country: '中国', tz: 'Asia/Shanghai' },
  { id: 'shanghai', name: '上海', country: '中国', tz: 'Asia/Shanghai' },
  { id: 'hongkong', name: '香港', country: '中国', tz: 'Asia/Hong_Kong' },
  { id: 'taipei', name: '台北', country: '中国', tz: 'Asia/Taipei' },
  { id: 'macau', name: '澳门', country: '中国', tz: 'Asia/Macau' },
  { id: 'tokyo', name: '东京', country: '日本', tz: 'Asia/Tokyo' },
  { id: 'seoul', name: '首尔', country: '韩国', tz: 'Asia/Seoul' },
  { id: 'singapore', name: '新加坡', country: '新加坡', tz: 'Asia/Singapore' },
  { id: 'bangkok', name: '曼谷', country: '泰国', tz: 'Asia/Bangkok' },
  { id: 'kualalumpur', name: '吉隆坡', country: '马来西亚', tz: 'Asia/Kuala_Lumpur' },
  { id: 'jakarta', name: '雅加达', country: '印度尼西亚', tz: 'Asia/Jakarta' },
  { id: 'manila', name: '马尼拉', country: '菲律宾', tz: 'Asia/Manila' },
  { id: 'hanoi', name: '河内', country: '越南', tz: 'Asia/Ho_Chi_Minh' },
  { id: 'delhi', name: '新德里', country: '印度', tz: 'Asia/Kolkata' },
  { id: 'mumbai', name: '孟买', country: '印度', tz: 'Asia/Kolkata' },
  { id: 'dubai', name: '迪拜', country: '阿联酋', tz: 'Asia/Dubai' },
  { id: 'riyadh', name: '利雅得', country: '沙特阿拉伯', tz: 'Asia/Riyadh' },
  { id: 'istanbul', name: '伊斯坦布尔', country: '土耳其', tz: 'Europe/Istanbul' },
  { id: 'tashkent', name: '塔什干', country: '乌兹别克斯坦', tz: 'Asia/Tashkent' },
  { id: 'moscow', name: '莫斯科', country: '俄罗斯', tz: 'Europe/Moscow' },
  { id: 'novosibirsk', name: '新西伯利亚', country: '俄罗斯', tz: 'Asia/Novosibirsk' },
  { id: 'vladivostok', name: '符拉迪沃斯托克', country: '俄罗斯', tz: 'Asia/Vladivostok' },
  { id: 'sydney', name: '悉尼', country: '澳大利亚', tz: 'Australia/Sydney' },
  { id: 'melbourne', name: '墨尔本', country: '澳大利亚', tz: 'Australia/Melbourne' },
  { id: 'brisbane', name: '布里斯班', country: '澳大利亚', tz: 'Australia/Brisbane' },
  { id: 'perth', name: '珀斯', country: '澳大利亚', tz: 'Australia/Perth' },
  { id: 'auckland', name: '奥克兰', country: '新西兰', tz: 'Pacific/Auckland' },
  { id: 'fiji', name: '苏瓦', country: '斐济', tz: 'Pacific/Fiji' },
  { id: 'honolulu', name: '檀香山', country: '美国', tz: 'Pacific/Honolulu' },
  { id: 'anchorage', name: '安克雷奇', country: '美国', tz: 'America/Anchorage' },
  { id: 'losangeles', name: '洛杉矶', country: '美国', tz: 'America/Los_Angeles' },
  { id: 'sanfrancisco', name: '旧金山', country: '美国', tz: 'America/Los_Angeles' },
  { id: 'seattle', name: '西雅图', country: '美国', tz: 'America/Los_Angeles' },
  { id: 'denver', name: '丹佛', country: '美国', tz: 'America/Denver' },
  { id: 'chicago', name: '芝加哥', country: '美国', tz: 'America/Chicago' },
  { id: 'houston', name: '休斯敦', country: '美国', tz: 'America/Chicago' },
  { id: 'newyork', name: '纽约', country: '美国', tz: 'America/New_York' },
  { id: 'washington', name: '华盛顿', country: '美国', tz: 'America/New_York' },
  { id: 'toronto', name: '多伦多', country: '加拿大', tz: 'America/Toronto' },
  { id: 'vancouver', name: '温哥华', country: '加拿大', tz: 'America/Vancouver' },
  { id: 'mexicocity', name: '墨西哥城', country: '墨西哥', tz: 'America/Mexico_City' },
  { id: 'saopaulo', name: '圣保罗', country: '巴西', tz: 'America/Sao_Paulo' },
  { id: 'buenosaires', name: '布宜诺斯艾利斯', country: '阿根廷', tz: 'America/Argentina/Buenos_Aires' },
  { id: 'lima', name: '利马', country: '秘鲁', tz: 'America/Lima' },
  { id: 'london', name: '伦敦', country: '英国', tz: 'Europe/London' },
  { id: 'paris', name: '巴黎', country: '法国', tz: 'Europe/Paris' },
  { id: 'berlin', name: '柏林', country: '德国', tz: 'Europe/Berlin' },
  { id: 'rome', name: '罗马', country: '意大利', tz: 'Europe/Rome' },
  { id: 'madrid', name: '马德里', country: '西班牙', tz: 'Europe/Madrid' },
  { id: 'amsterdam', name: '阿姆斯特丹', country: '荷兰', tz: 'Europe/Amsterdam' },
  { id: 'zurich', name: '苏黎世', country: '瑞士', tz: 'Europe/Zurich' },
  { id: 'stockholm', name: '斯德哥尔摩', country: '瑞典', tz: 'Europe/Stockholm' },
  { id: 'oslo', name: '奥斯陆', country: '挪威', tz: 'Europe/Oslo' },
  { id: 'helsinki', name: '赫尔辛基', country: '芬兰', tz: 'Europe/Helsinki' },
  { id: 'athens', name: '雅典', country: '希腊', tz: 'Europe/Athens' },
  { id: 'warsaw', name: '华沙', country: '波兰', tz: 'Europe/Warsaw' },
  { id: 'prague', name: '布拉格', country: '捷克', tz: 'Europe/Prague' },
  { id: 'vienna', name: '维也纳', country: '奥地利', tz: 'Europe/Vienna' },
  { id: 'lisbon', name: '里斯本', country: '葡萄牙', tz: 'Europe/Lisbon' },
  { id: 'cairo', name: '开罗', country: '埃及', tz: 'Africa/Cairo' },
  { id: 'johannesburg', name: '约翰内斯堡', country: '南非', tz: 'Africa/Johannesburg' },
  { id: 'nairobi', name: '内罗毕', country: '肯尼亚', tz: 'Africa/Nairobi' },
  { id: 'lagos', name: '拉各斯', country: '尼日利亚', tz: 'Africa/Lagos' },
  { id: 'casablanca', name: '卡萨布兰卡', country: '摩洛哥', tz: 'Africa/Casablanca' },
];

const CITY_MAP = {};
CITIES.forEach((c) => { CITY_MAP[c.id] = c; });

/** 截图中的默认城市：纽约 / 伦敦 / 莫斯科 */
const DEFAULT_CITY_IDS = ['newyork', 'london', 'moscow'];
